export enum FeedReactionType {
  PRAISE = 'PRAISE',
  LIKE = 'LIKE',
  APPRECIATION = 'APPRECIATION',
  EMPATHY = 'EMPATHY',
  INTEREST = 'INTEREST',
  ENTERTAINMENT = 'ENTERTAINMENT',
  MAYBE = 'MAYBE',
}
